directoryPaths = ["/Users/volkanalkilic/Downloads", "/Users/volkanalkilic/Downloads"]
includeSubdirectories = false
fileTypes = "toml,log"               #Use *.* to all files
createdEventEnabled = true
changedEventEnabled = true
deletedEventEnabled = true


brokerHostname = "127.0.0.1"
brokerPort = 1883
brokerUsername = "username"
brokerPassword = "password"
topic = "files/upload"
protocolVersion = 3                 # 3 = V310, 4 = V311, 5 = V500 
sslEnabled = false
sslCertificatePath = "client.pfx"

compress = false

